disabled_rules: # rule identifiers to exclude from running
  # - colon
  - comma
  # - control_statement
  - variable_name
  - force_cast
  - large_tuple
  - notification_center_detachment
  - nesting
  - function_parameter_count
  - trailing_whitespace # <---------
opt_in_rules: # some rules are only opt-in
  - empty_count

line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
